# Production values for volunteer-service

replicaCount: 2

image:
  repository: $(aws ssm get-parameter --name /solidarytech/production/ecr/volunteer-service-url --query Parameter.Value --output text)
  pullPolicy: Always
  tag: $(git rev-parse --short HEAD)

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
